# This workflow will build and deploy using Cloud Run.
name: Cloud Run Continuous Deployment
on:
  push:
    # TODO: change 'none' to 'main' to enable the workflow to run
    branches: 'main'
  release:
    types: [published]
env:
  PROJECT_ID: 'e3-ai-shoe-starter' # TODO: update to your Google Cloud project ID
  SERVICE_NAME: 'e3-service' # TODO: update to your service name (name of your team's webapp!)
  SERVICE_REGION: 'us-central1'
  SERVICE_ACCOUNT: '17429202269-compute@developer.gserviceaccount.com' # TODO: update to your Cloud service account
  WORKLOAD_IDENTITY_PROVIDER: 'projects/17429202269/locations/global/workloadIdentityPools/github/providers/project-repo' #TODO: update to your workload identity provider
  AUTH0_DOMAIN: '${{ secrets.AUTH0_DOMAIN }}'
  AUTH0_CLIENT_ID: '${{ secrets.AUTH0_CLIENT_ID }}'
  AUTH0_CLIENT_SECRET: '${{ secrets.AUTH0_CLIENT_SECRET }}'
  AUTH0_CALLBACK_URL: '${{ secrets.AUTH0_CALLBACK_URL }}'
jobs:
  py-checks:
    uses: ./.github/workflows/python-checks.yml
    
  build-deploy:
    name: 'Build and deploy using Cloud Run'
    runs-on: ubuntu-latest
    needs: py-checks
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v4'
    # Authorize GitHub to connect to your service account
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: '${{ env.SERVICE_ACCOUNT }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        version: '>= 363.0.0'
    
    - name: 'Test BigQuery Access'
      run: |
        pip install --quiet google-cloud-bigquery
        python -c "from google.cloud import bigquery; client = bigquery.Client(); query = 'SELECT CURRENT_DATE() AS today'; rows = client.query(query).result(); [print('✅ BigQuery working. Today is:', row.today) for row in rows]"
    
    - name: 'Configure docker for GCP'
      run: 'gcloud auth configure-docker'
    
    - name: 'Build and push Docker image'
      uses: 'docker/build-push-action@v5'
      with:
        context: .
        push: true
        tags: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}'
    
    - id: 'Deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: '${{ env.SERVICE_NAME }}'
        image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest'
        region: '${{ env.SERVICE_REGION }}'
        env_vars: |
          AUTH0_DOMAIN=${{ env.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID=${{ env.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET=${{ env.AUTH0_CLIENT_SECRET }}
          AUTH0_CALLBACK_URL=${{ env.AUTH0_CALLBACK_URL }}
    
    - name: 'Display deployed app URL'
      run: 'curl "${{ steps.Deploy.outputs.url }}"'
